version: "3.7"
services:
  mysql:
    image: mysql:8.0.17
    container_name: base-prac-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: basic_development
      MYSQL_USER: rails
      MYSQL_PASSWORD: rails
    ports:
      - "3306:3306"
  web:
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sandbox
    ports:
      - "3000:3000"
    links:
      - mysql

